"""Pi-hole v Dockeru. Dvě instance s replikací gravity databáze.

Architektura:
  - Pi-hole je DNS resolver. Naše Samba DNS poslouchá na :53, takže
    Pi-hole běží na portu cfg.pihole.dns_port (default 5353) a Samba ho
    používá jako forwarder (smb.conf: `dns forwarder = 127.0.0.1#5353`).
  - DC1 i DC2 mají vlastní instanci. Klienti volí podle DHCP nebo
    failover na DC2 když DC1 padne.
  - Replikace přes gravity-sync (samostatný kontejner / cron job).

Bloky pro konkrétní počítače:
  Pi-hole API umí přidávat klienty do skupin a skupinám přiřazovat
  blocklisty. Management engine bude přes tuto API spravovat
  per-MAC/per-IP blokování.
"""
from __future__ import annotations

import secrets
from pathlib import Path
from textwrap import dedent

from .base import BaseInstaller


PIHOLE_DIR = Path("/opt/pihole")


class PiholeInstaller(BaseInstaller):
    name = "Pi-hole (Docker)"

    def install(self, *, instance: int = 1) -> None:
        PIHOLE_DIR.mkdir(parents=True, exist_ok=True)
        (PIHOLE_DIR / "etc-pihole").mkdir(exist_ok=True)
        (PIHOLE_DIR / "etc-dnsmasq.d").mkdir(exist_ok=True)

        compose = self._compose_yaml(instance)
        self.runner.write_file(PIHOLE_DIR / "docker-compose.yml", compose, mode=0o600)

        # Spustit
        self.runner.sh(
            ["docker", "compose", "-f", str(PIHOLE_DIR / "docker-compose.yml"), "up", "-d"],
        )

    def verify(self) -> None:
        r = self.runner.sh(["docker", "ps", "--filter", "name=pihole", "--format", "{{.Status}}"], check=False)
        from rich.console import Console
        Console().print(f"[green]Pi-hole status:[/] {r.stdout.strip()}")

    def _compose_yaml(self, instance: int) -> str:
        # Která IP nás identifikuje - DC1 nebo DC2
        my_ip = (
            str(self.cfg.servers.dc1.ip) if instance == 1
            else str(self.cfg.servers.dc2.ip)
        )
        dns_port = self.cfg.pihole.dns_port
        web_port = self.cfg.pihole.web_port

        # Upstream DNS oddělené ;
        upstreams = ";".join(str(d) for d in self.cfg.pihole.upstream_dns)

        return dedent(f"""\
            # Pi-hole instance {instance} - generated by domain-manager
            services:
              pihole:
                container_name: pihole
                image: pihole/pihole:latest
                restart: unless-stopped
                ports:
                  - "{my_ip}:{dns_port}:53/tcp"
                  - "{my_ip}:{dns_port}:53/udp"
                  - "{my_ip}:{web_port}:80/tcp"
                environment:
                  TZ: "Europe/Prague"
                  FTLCONF_webserver_api_password: "{self.cfg.pihole.webpassword}"
                  FTLCONF_dns_upstreams: "{upstreams}"
                  FTLCONF_dns_listeningMode: "all"
                  # Reklamní listy - výchozí Pi-hole default je rozumný
                volumes:
                  - ./etc-pihole:/etc/pihole
                  - ./etc-dnsmasq.d:/etc/dnsmasq.d
                cap_add:
                  - NET_ADMIN
                  - SYS_NICE
            """)
