"""Instalace primárního Samba AD DC na Ubuntu 26.04.

Postup:
  1) Nastavit hostname a /etc/hosts
  2) Nastavit statickou IP přes netplan (idempotentně - zálohuje původní)
  3) Zastavit a maskovat smbd/nmbd/winbind (kolidují s samba-ad-dc)
  4) apt install samba-ad-dc + závislosti
  5) samba-tool domain provision (interaktivně NE - všechno z configu)
  6) Konfigurace Kerberos (krb5.conf)
  7) Spustit a enable samba-ad-dc
  8) Smoke test (samba-tool domain info, kinit, ping)

Specifika 26.04 (Resolute Raccoon):
  - samba-ad-dc je samostatný balíček (nestačí jen samba)
  - SMB3 Unix Extensions enabled by default
  - NetBIOS je defaultně vypnutý (nemusíme řešit nmbd)
  - SSSD běží pod uživatelem sssd (ne root)
"""
from __future__ import annotations

import shutil
import socket
import time
from pathlib import Path
from textwrap import dedent

from rich.console import Console

from .base import BaseInstaller

console = Console()


class SambaDC1Installer(BaseInstaller):
    name = "Samba AD DC (primární)"

    # samba-ad-dc je metapackage co stáhne vše potřebné
    PACKAGES = [
        "samba-ad-dc",
        "samba",
        "krb5-user",
        "krb5-config",
        "smbclient",
        "ldb-tools",
        "winbind",  # pro nss_winbind
        "libnss-winbind",
        "libpam-winbind",
        "chrony",   # NTP - AD klienti vyžadují synchronizovaný čas (skew < 5 min)
        "dnsutils", # dig, host - pro ověření DNS
    ]

    def preflight(self) -> None:
        # Hostname kontrola: musí matchovat config
        actual = socket.gethostname()
        expected = self.cfg.servers.dc1.hostname
        if actual != expected:
            console.print(
                f"[yellow]Pozor:[/] hostname je '{actual}', config očekává '{expected}'. "
                f"Nastavím přes hostnamectl."
            )

        # Kontrola existující Samby (nechceme přepsat běžící DC)
        if Path("/var/lib/samba/private/sam.ldb").exists():
            raise RuntimeError(
                "Vypadá to, že Samba AD už je provisioned (/var/lib/samba/private/sam.ldb existuje). "
                "Pro re-provision smažte adresář /var/lib/samba (zničí to data!) "
                "nebo použijte --skip-provision."
            )

    def install(self, *, skip_provision: bool = False) -> None:
        self._setup_hostname()
        self._setup_network()
        self._stop_conflicting_services()
        self._install_packages()
        self._setup_chrony()
        if not skip_provision:
            self._provision_domain()
        self._setup_krb5_conf()
        self._enable_samba_ad_dc()

    def verify(self) -> None:
        time.sleep(2)
        if not self.runner.is_active("samba-ad-dc"):
            console.print("[red]✗ samba-ad-dc neběží[/]")
            self.runner.sh("systemctl status samba-ad-dc --no-pager", check=False)
            return
        # samba-tool domain info na localhostu
        r = self.runner.sh(
            ["samba-tool", "domain", "info", "127.0.0.1"],
            check=False,
        )
        if r.ok:
            console.print(f"[green]✓ samba-tool domain info:[/]\n{r.stdout}")
        else:
            console.print(f"[yellow]Pozor: samba-tool selhal: {r.stderr}[/]")

    # --- jednotlivé kroky -------------------------------------------------

    def _setup_hostname(self) -> None:
        hostname = self.cfg.servers.dc1.hostname
        realm_lower = self.cfg.domain.realm.lower()
        fqdn = f"{hostname}.{realm_lower}"
        ip = str(self.cfg.servers.dc1.ip)

        self.runner.sh(["hostnamectl", "set-hostname", hostname])

        # /etc/hosts - důležité aby FQDN ukazovalo na statickou IP, ne 127.0.1.1
        hosts_content = dedent(f"""\
            127.0.0.1   localhost
            {ip}   {fqdn} {hostname}

            # IPv6
            ::1         ip6-localhost ip6-loopback
            fe00::0     ip6-localnet
            ff00::0     ip6-mcastprefix
            ff02::1     ip6-allnodes
            ff02::2     ip6-allrouters
            """)
        self.runner.write_file(Path("/etc/hosts"), hosts_content, mode=0o644)

    def _setup_network(self) -> None:
        """Statická IP přes netplan. Idempotentně."""
        dc = self.cfg.servers.dc1
        # Klient na DC1 by měl dotazovat sám sebe (Samba DNS), ne externí
        netplan = dedent(f"""\
            # Generated by domain-manager
            network:
              version: 2
              ethernets:
                {dc.interface}:
                  dhcp4: false
                  addresses:
                    - {dc.ip}/{self._prefix_len()}
                  routes:
                    - to: default
                      via: {self.cfg.network.gateway}
                  nameservers:
                    addresses:
                      - {dc.ip}
                      - {self.cfg.servers.dc2.ip}
                    search:
                      - {self.cfg.domain.realm.lower()}
            """)
        changed = self.runner.write_file(
            Path("/etc/netplan/99-domain-manager.yaml"),
            netplan,
            mode=0o600,
        )
        if changed:
            self.runner.sh(["netplan", "apply"])

    def _prefix_len(self) -> int:
        import ipaddress
        return ipaddress.ip_network(self.cfg.network.subnet, strict=False).prefixlen

    def _stop_conflicting_services(self) -> None:
        """smbd, nmbd a winbind nesmí běžet samostatně - sambu spouští samba-ad-dc unit."""
        for unit in ("smbd", "nmbd", "winbind"):
            self.runner.sh(["systemctl", "stop", unit], check=False)
            self.runner.sh(["systemctl", "disable", unit], check=False)
            self.runner.sh(["systemctl", "mask", unit], check=False)
        # samba-ad-dc je defaultně maskovaný - odmaskujeme po provisionu

    def _install_packages(self) -> None:
        self.runner.apt_update()
        self.runner.apt_install(self.PACKAGES)

    def _setup_chrony(self) -> None:
        """Bez NTP synchronizace AD neumí Kerberos."""
        # Defaultní chrony stačí. Zajistíme jen že běží.
        self.runner.systemd_enable_now("chrony")

    def _provision_domain(self) -> None:
        """Vytvoří doménu pomocí samba-tool. JEDNORÁZOVÁ operace."""
        # Backup případného starého smb.conf
        smb_conf = Path("/etc/samba/smb.conf")
        if smb_conf.exists():
            backup = smb_conf.with_suffix(".conf.before-provision")
            shutil.copy(smb_conf, backup)
            console.print(f"[dim]záloha smb.conf: {backup}[/]")
            smb_conf.unlink()

        # Hlavní příkaz. --use-rfc2307 přidá POSIX atributy pro unix klienty.
        cmd = [
            "samba-tool", "domain", "provision",
            f"--realm={self.cfg.domain.realm}",
            f"--domain={self.cfg.domain.netbios}",
            "--server-role=dc",
            "--use-rfc2307",
            f"--dns-backend=SAMBA_INTERNAL",
            f"--adminpass={self.cfg.domain.admin_password}",
            f"--option=interfaces=lo {self.cfg.servers.dc1.interface}",
            "--option=bind interfaces only=yes",
        ]
        console.print("[blue]→[/] samba-tool domain provision (může trvat minutu)...")
        self.runner.sh(cmd, sensitive=True)

        # DNS forwarder do smb.conf
        self._configure_dns_forwarder()

    def _configure_dns_forwarder(self) -> None:
        """Přidá dns forwarder do smb.conf (kam posílat dotazy, které doména neřeší)."""
        smb_conf = Path("/etc/samba/smb.conf")
        content = smb_conf.read_text(encoding="utf-8")
        forwarder = str(self.cfg.domain.dns_forwarder)
        if "dns forwarder" in content:
            console.print("[dim]dns forwarder už nastaven[/]")
            return
        # Přidat do [global] sekce
        content = content.replace(
            "[global]",
            f"[global]\n\tdns forwarder = {forwarder}",
            1,
        )
        self.runner.write_file(smb_conf, content, mode=0o644)

    def _setup_krb5_conf(self) -> None:
        """Samba si při provisioningu vygeneruje krb5.conf v /var/lib/samba/private/.
        Slinkujeme to do /etc/krb5.conf pro systémové nástroje (kinit, ldapsearch)."""
        src = Path("/var/lib/samba/private/krb5.conf")
        dst = Path("/etc/krb5.conf")
        if src.exists():
            if dst.exists() and not dst.is_symlink():
                shutil.copy(dst, dst.with_suffix(".conf.orig"))
                dst.unlink()
            if not dst.exists():
                dst.symlink_to(src)
                console.print(f"[blue]→[/] symlink {dst} -> {src}")

    def _enable_samba_ad_dc(self) -> None:
        # samba-ad-dc je defaultně masked aby ho nikdo nespustil omylem
        self.runner.sh(["systemctl", "unmask", "samba-ad-dc"])
        self.runner.systemd_enable_now("samba-ad-dc")
