"""Instalace primárního Samba AD DC na Ubuntu 26.04.

Postup:
  1) Nastavit hostname a /etc/hosts
  2) Nastavit statickou IP přes netplan (idempotentně - zálohuje původní)
  3) Zastavit a maskovat smbd/nmbd/winbind (kolidují s samba-ad-dc)
  4) apt install samba-ad-dc + závislosti
  5) samba-tool domain provision (interaktivně NE - všechno z configu)
  6) Konfigurace Kerberos (krb5.conf)
  7) Spustit a enable samba-ad-dc
  8) Smoke test (samba-tool domain info, kinit, ping)

Specifika 26.04 (Resolute Raccoon):
  - samba-ad-dc je samostatný balíček (nestačí jen samba)
  - SMB3 Unix Extensions enabled by default
  - NetBIOS je defaultně vypnutý (nemusíme řešit nmbd)
  - SSSD běží pod uživatelem sssd (ne root)
"""
from __future__ import annotations

import shutil
import socket
import time
from pathlib import Path
from textwrap import dedent

from rich.console import Console

from .base import BaseInstaller

console = Console()


class SambaDC1Installer(BaseInstaller):
    name = "Samba AD DC (primární)"

    # samba-ad-dc je metapackage co stáhne vše potřebné
    PACKAGES = [
        "samba-ad-dc",
        "samba",
        "krb5-user",
        "krb5-config",
        "smbclient",
        "ldb-tools",
        "winbind",  # pro nss_winbind
        "libnss-winbind",
        "libpam-winbind",
        "chrony",   # NTP - AD klienti vyžadují synchronizovaný čas (skew < 5 min)
        "dnsutils", # dig, host - pro ověření DNS
    ]

    def preflight(self) -> None:
        # Hostname kontrola: musí matchovat config
        actual = socket.gethostname()
        expected = self.cfg.servers.dc1.hostname
        if actual != expected:
            console.print(
                f"[yellow]Pozor:[/] hostname je '{actual}', config očekává '{expected}'. "
                f"Nastavím přes hostnamectl."
            )

        # Kontrola existující Samby (nechceme přepsat běžící DC)
        if Path("/var/lib/samba/private/sam.ldb").exists():
            raise RuntimeError(
                "Vypadá to, že Samba AD už je provisioned (/var/lib/samba/private/sam.ldb existuje). "
                "Pro re-provision smažte adresář /var/lib/samba (zničí to data!) "
                "nebo použijte --skip-provision."
            )

    def install(self, *, skip_provision: bool = False) -> None:
        self._setup_hostname()
        self._setup_network()
        self._stop_conflicting_services()
        self._disable_systemd_resolved()   # musí být před startem Samby (port 53 konflikt)
        self._install_packages()
        self._setup_chrony()
        if not skip_provision:
            self._provision_domain()
        self._setup_krb5_conf()
        self._enable_samba_ad_dc()

    def verify(self) -> None:
        time.sleep(2)
        if not self.runner.is_active("samba-ad-dc"):
            console.print("[red]✗ samba-ad-dc neběží[/]")
            self.runner.sh("systemctl status samba-ad-dc --no-pager", check=False)
            return
        # samba-tool domain info na localhostu
        r = self.runner.sh(
            ["samba-tool", "domain", "info", "127.0.0.1"],
            check=False,
        )
        if r.ok:
            console.print(f"[green]✓ samba-tool domain info:[/]\n{r.stdout}")
        else:
            console.print(f"[yellow]Pozor: samba-tool selhal: {r.stderr}[/]")

    # --- jednotlivé kroky -------------------------------------------------

    def _setup_hostname(self) -> None:
        hostname = self.cfg.servers.dc1.hostname
        realm_lower = self.cfg.domain.realm.lower()
        fqdn = f"{hostname}.{realm_lower}"
        ip = str(self.cfg.servers.dc1.ip)

        self.runner.sh(["hostnamectl", "set-hostname", hostname])

        # /etc/hosts - důležité aby FQDN ukazovalo na statickou IP, ne 127.0.1.1
        hosts_content = dedent(f"""\
            127.0.0.1   localhost
            {ip}   {fqdn} {hostname}

            # IPv6
            ::1         ip6-localhost ip6-loopback
            fe00::0     ip6-localnet
            ff00::0     ip6-mcastprefix
            ff02::1     ip6-allnodes
            ff02::2     ip6-allrouters
            """)
        self.runner.write_file(Path("/etc/hosts"), hosts_content, mode=0o644)

    def _setup_network(self) -> None:
        """Statická IP přes netplan. Idempotentně."""
        dc = self.cfg.servers.dc1
        iface = self._detect_interface(dc.interface)
        forwarder = str(self.cfg.domain.dns_forwarder)
        static_ip = str(dc.ip)

        netplan = dedent(f"""\
            # Generated by domain-manager
            network:
              version: 2
              ethernets:
                {iface}:
                  dhcp4: false
                  addresses:
                    - {static_ip}/{self._prefix_len()}
                  routes:
                    - to: default
                      via: {self.cfg.network.gateway}
                  nameservers:
                    addresses:
                      - 127.0.0.1
                      - {forwarder}
                    search:
                      - {self.cfg.domain.realm.lower()}
            """)
        changed = self.runner.write_file(
            Path("/etc/netplan/99-domain-manager.yaml"),
            netplan,
            mode=0o600,
        )
        if changed:
            self._warn_ip_change(static_ip)
            self.runner.sh(["netplan", "apply"])
            self._verify_gateway()

    def _prefix_len(self) -> int:
        import ipaddress
        return ipaddress.ip_network(self.cfg.network.subnet, strict=False).prefixlen

    def _detect_interface(self, configured: str) -> str:
        """Ověří, že interface z configu existuje. Pokud ne, vrátí první aktivní a varuje."""
        import os
        sys_net = Path("/sys/class/net")
        if (sys_net / configured).exists():
            return configured
        # Interface neexistuje — hledáme alternativu
        candidates = [
            d.name for d in sys_net.iterdir()
            if d.name not in ("lo",) and (sys_net / d.name / "operstate").exists()
        ]
        if candidates:
            found = candidates[0]
            console.print(
                f"[yellow]Pozor:[/] interface '{configured}' z configu neexistuje. "
                f"Použiji '{found}'. Opravte servers.dc1.interface v config.yaml."
            )
            return found
        console.print(f"[red]Nepodařilo se najít síťový interface (config: '{configured}')[/]")
        return configured

    def _warn_ip_change(self, new_ip: str) -> None:
        """Upozornění před netplan apply — SSH se odpojí pokud stroj měl jinou IP."""
        import subprocess
        # Zjistíme aktuální IP na rozhraní
        current_ips: list[str] = []
        try:
            r = subprocess.run(
                ["ip", "-4", "-o", "addr", "show"],
                capture_output=True, text=True,
            )
            for line in r.stdout.splitlines():
                parts = line.split()
                if len(parts) >= 4 and parts[1] != "lo":
                    ip = parts[3].split("/")[0]
                    current_ips.append(ip)
        except Exception:
            pass

        if new_ip in current_ips:
            console.print(f"[green]✓[/] statická IP {new_ip} je už nastavená, netplan apply nezmění adresu")
            return

        console.print(f"""
[bold yellow]⚠  UPOZORNĚNÍ — ZMĚNA IP ADRESY[/]

  Aktuální IP:  {', '.join(current_ips) or '(neznámá)'}
  Nová statická IP: [bold]{new_ip}[/]

  Po [bold]netplan apply[/] bude stroj dostupný na [bold]{new_ip}[/].
  Pokud jste připojeni přes SSH na starou adresu, spojení se přeruší.

  [dim]Poznámka: Samba AD DC NESPOUŠTÍ DHCP server — Kea DHCP
  je samostatná komponenta. Původní DHCP server v síti
  nevypínejte, dokud nenainstalujete a nespustíte Kea.[/]

  Čekám 10 sekund — připojte se na {new_ip} a pokračujte tam.
""")
        import time
        for i in range(10, 0, -1):
            console.print(f"  [dim]{i}...[/]", end="\r")
            time.sleep(1)
        console.print()

    def _verify_gateway(self) -> None:
        """Ověří, že gateway je dostupná po aplikaci netplanu."""
        gw = str(self.cfg.network.gateway)
        r = self.runner.sh(["ping", "-c", "2", "-W", "3", gw], check=False)
        if r.ok:
            console.print(f"[green]✓[/] gateway {gw} dostupná")
        else:
            console.print(
                f"[red]✗ Gateway {gw} není dostupná po netplan apply![/]\n"
                f"Zkontrolujte: servers.dc1.interface, network.gateway, adresy v configu.\n"
                f"SSH připojení může být přerušeno."
            )

    def _stop_conflicting_services(self) -> None:
        """smbd, nmbd a winbind nesmí běžet samostatně - sambu spouští samba-ad-dc unit."""
        for unit in ("smbd", "nmbd", "winbind"):
            self.runner.sh(["systemctl", "stop", unit], check=False)
            self.runner.sh(["systemctl", "disable", unit], check=False)
            self.runner.sh(["systemctl", "mask", unit], check=False)
        # samba-ad-dc je defaultně maskovaný - odmaskujeme po provisionu

    def _disable_systemd_resolved(self) -> None:
        """Samba AD DC potřebuje port 53. systemd-resolved má stub listener na 53
        a způsobuje konflikt → DNS přestane fungovat → SSH se ztratí.
        Standardní postup pro Samba DC na Ubuntu 22+/24+."""
        console.print("[blue]→[/] zakazuji systemd-resolved stub listener (port 53 pro Samba)...")

        # Zakázat stub listener v konfiguraci systemd-resolved
        resolved_conf = Path("/etc/systemd/resolved.conf.d/no-stub.conf")
        self.runner.write_file(
            resolved_conf,
            "[Resolve]\nDNSStubListener=no\n",
            mode=0o644,
        )
        self.runner.sh(["systemctl", "restart", "systemd-resolved"], check=False)

        # /etc/resolv.conf — přepsat na přímý nameserver (127.0.0.1 = Samba DNS)
        # Ubuntu defaultně má symlink na /run/systemd/resolve/stub-resolv.conf
        resolv = Path("/etc/resolv.conf")
        if resolv.is_symlink():
            resolv.unlink()
        realm_lower = self.cfg.domain.realm.lower()
        forwarder = str(self.cfg.domain.dns_forwarder)
        self.runner.write_file(
            resolv,
            f"nameserver 127.0.0.1\nnameserver {forwarder}\nsearch {realm_lower}\n",
            mode=0o644,
            backup=False,  # symlink by backup nešel
        )

    def _install_packages(self) -> None:
        self.runner.apt_update()
        self.runner.apt_install(self.PACKAGES)

    def _setup_chrony(self) -> None:
        """Bez NTP synchronizace AD neumí Kerberos."""
        # Defaultní chrony stačí. Zajistíme jen že běží.
        self.runner.systemd_enable_now("chrony")

    def _provision_domain(self) -> None:
        """Vytvoří doménu pomocí samba-tool. JEDNORÁZOVÁ operace."""
        # Backup případného starého smb.conf
        smb_conf = Path("/etc/samba/smb.conf")
        if smb_conf.exists():
            backup = smb_conf.with_suffix(".conf.before-provision")
            shutil.copy(smb_conf, backup)
            console.print(f"[dim]záloha smb.conf: {backup}[/]")
            smb_conf.unlink()

        # Hlavní příkaz. --use-rfc2307 přidá POSIX atributy pro unix klienty.
        cmd = [
            "samba-tool", "domain", "provision",
            f"--realm={self.cfg.domain.realm}",
            f"--domain={self.cfg.domain.netbios}",
            "--server-role=dc",
            "--use-rfc2307",
            f"--dns-backend=SAMBA_INTERNAL",
            f"--adminpass={self.cfg.domain.admin_password}",
            f"--option=interfaces=lo {self.cfg.servers.dc1.interface}",
            "--option=bind interfaces only=yes",
        ]
        console.print("[blue]→[/] samba-tool domain provision (může trvat minutu)...")
        self.runner.sh(cmd, sensitive=True)

        # DNS forwarder do smb.conf
        self._configure_dns_forwarder()

    def _configure_dns_forwarder(self) -> None:
        """Přidá dns forwarder do smb.conf (kam posílat dotazy, které doména neřeší)."""
        smb_conf = Path("/etc/samba/smb.conf")
        content = smb_conf.read_text(encoding="utf-8")
        forwarder = str(self.cfg.domain.dns_forwarder)
        if "dns forwarder" in content:
            console.print("[dim]dns forwarder už nastaven[/]")
            return
        # Přidat do [global] sekce
        content = content.replace(
            "[global]",
            f"[global]\n\tdns forwarder = {forwarder}",
            1,
        )
        self.runner.write_file(smb_conf, content, mode=0o644)

    def _setup_krb5_conf(self) -> None:
        """Samba si při provisioningu vygeneruje krb5.conf v /var/lib/samba/private/.
        Slinkujeme to do /etc/krb5.conf pro systémové nástroje (kinit, ldapsearch)."""
        src = Path("/var/lib/samba/private/krb5.conf")
        dst = Path("/etc/krb5.conf")
        if src.exists():
            if dst.exists() and not dst.is_symlink():
                shutil.copy(dst, dst.with_suffix(".conf.orig"))
                dst.unlink()
            if not dst.exists():
                dst.symlink_to(src)
                console.print(f"[blue]→[/] symlink {dst} -> {src}")

    def _enable_samba_ad_dc(self) -> None:
        # samba-ad-dc je defaultně masked aby ho nikdo nespustil omylem
        self.runner.sh(["systemctl", "unmask", "samba-ad-dc"])
        self.runner.systemd_enable_now("samba-ad-dc")
